### ISSUE TITLE
question: XML parser: arbor.net - fastflux.xml

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#244]
sample config:

```
parser: xml
defaults:
  provider: 'atlas.arbor.net'
  tlp: amber
  confidence: 70

feeds:
  flux:
    remote: 'http://atlas.arbor.net/summary/fastflux.xml'
    node: newest
    map:
      - domain
    values:
      - observable
```

cif-smrt command:

```
/opt/cif/bin/cif-smrt --testmode -c -d -r /etc/cif/rules/example/arbor_fastflux.xml
```

debug output:

```
$VAR1 = {'tlp' => 'amber','provider' => 'atlas.arbor.net','map' => ['domain'],'node' => 'newest','reporttime' => '2015-06-12T20:10:49Z','altid' => 'http://atlas.arbor.net/summary/fastflux.xml','group' => 'everyone','observable' => 'stjohnhos.co.uknewflirtingdates.infoswitch-to-dish.comcom-jun-30.usmybestchoice.bizjoxbox.comafghandosti.comcom-june-19.usgetghosted.comcom-jun-19.us','confidence' => '70'};
```

instead of parsing each domain as a separate observable, the parser munged them all into one record:

```
'observable' => 'stjohnhos.co.uknewflirtingdates.infoswitch-to-dish.comcom-jun-30.usmybestchoice.bizjoxbox.comafghandosti.comcom-june-19.usgetghosted.comcom-jun-19.us',
```

Is this a bug in the config or a bug in the parser?
