### ISSUE TITLE
XML parser error (cleanmx)

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/massive-octo-spice#294]
Trying to migrate the cleanmx.cfg file I found the following error:

.yml file
```
parser: xml
defaults:
  provider: support.clean-mx.de
  altid_tlp: amber
  tlp: amber
  confidence: 85
feeds:
  malware:
    remote: 'http://support.clean-mx.de/clean-mx/xmlviruses.php?'
    altid: 'http://support.clean-mx.de/clean-mx/viruses.php?id=<id>'
    node: entry
    map:
      - first
      - virusname
      - url
    values:
      - lasttime
      - description
      - observable
    tags: malware
```

cif_smrt cmd:
```
sudo su - cif -c "/opt/cif/bin/cif-smrt --testmode -c -d -r /etc/cif/rules/example/cleanmx.yml" &> /tmp/cleanmx
```

error:
```
[2015-07-22T12:41:33,893Z][ERROR][main:347]: failed to process data, skipping...
[2015-07-22T12:41:33,893Z][ERROR][main:349]: Assertion failed! at /usr/local/share/perl/5.18.2/Carp/Assert.pm line 282. Carp::Assert::assert(undef) called at /opt/cif/bin/../lib/perl5/CIF/Rule.pm line 134    CIF::Rule::_merge_defaults('CIF::Rule=HASH(0x49ddc80)', 'HASH(0x4f75c08)') called at /opt/cif/bin/../lib/perl5/CIF/Rule.pm line 50      CIF::Rule::process('CIF::Rule=HASH(0x49ddc80)', 'HASH(0x4f75c08)') called at /opt/cif/bin/../lib/perl5/CIF/Smrt.pm line 154     CIF::Smrt::process('CIF::Smrt=HASH(0x1f8dcb8)') called at /opt/cif/bin/cif-smrt line 341        main::try {...} () called at /usr/share/perl5/Try/Tiny.pm line 81       eval {...} called at /usr/share/perl5/Try/Tiny.pm line 72       Try::Tiny::try('CODE(0x4a274a8)', 'Try::Tiny::Catch=REF(0x2ac7a80)') called at /opt/cif/bin/cif-smrt line 344   main::_main() called at /opt/cif/bin/cif-smrt line 234
```

It appears the XML is being parsed correctly:
```
[2015-07-22T12:41:33,388Z][DEBUG][CIF::Smrt::Parser::Xml:40]: <entry>
        <line>1</line>
        <id>77578662</id>
        <first>1437564646</first>
        <last>0</last>
        <md5>997c9b92cfac5731d90e050825869d5f</md5>
        <virustotal>http://www.virustotal.com/latest-report.html?resource=997c9b92cfac5731d90e050825869d5f</virustotal>
        <vt_score>4/58 (6.9%)</vt_score>
        <scanner>Ikarus</scanner>
        <virusname><![CDATA[PUA.BundleLoader]]></virusname>
        <url><![CDATA[http://www.softfreeway.com/distributives/SombraSetup.exe]]></url>
        <recent>up</recent>
        <response>alive</response>
        <ip>31.211.31.232</ip>
        <as>AS31036</as>
        <review>31.211.31.232</review>
        <domain>softfreeway.com</domain>
        <country>RU</country>
        <source>RIPE</source>
        <email>lir@nts.su</email>
        <inetnum>31.211.0.0 - 31.211.127.255</inetnum>
        <netname>RU-NEWTELESYSTEMS-20110505</netname>
        <descr><![CDATA[New Telesystems - TV, Ltd.New Telesystems, Ltd.New Telesystems, Ltd.]]></descr>
        <ns1>ns2.softfreeway.com</ns1>
        <ns2>ns.softfreeway.com</ns2>
        <ns3/>
        <ns4/>
        <ns5/>
</entry>
```

(adding ```print Dumper(@array)``` to /opt/cif/lib/perl5/CIF/Smrt/Parser/Xml.pm)
```
$VAR1 = {
          'description' => 'PUA.BundleLoader',
          'lasttime' => '1437564646',
          'observable' => 'http://www.softfreeway.com/distributives/SombraSetup.exe'
        };
```

It would appear the XML is being parsed correctly on the way in and on the way out. Thoughts on error?

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/py-cifcleanmx

**Comment by giovino** [comment]
Can you be more verbose on the question? I realize you could always parse the feed out of band (py-cifcleanmx).

**Comment by wesyoung** [comment]
right now, we can't "keep track of where we left off" and cleanmx gives us the entire database each time... so we should be using the cleanmx-app and try to build that "bookmark" functionality into v3 fetchers..

that being said, you're missing "id" in your mapping since you're using it as a var..

```yaml
parser: xml
defaults:
  provider: support.clean-mx.de
  altid_tlp: amber
  tlp: amber
  confidence: 85
feeds:
  malware:
    remote: 'http://support.clean-mx.de/clean-mx/xmlviruses.php?'
    altid: 'http://support.clean-mx.de/clean-mx/viruses.php?id=<id>'
    node: entry
    map:
      - first
      - virusname
      - url
      - id
    values:
      - lasttime
      - description
      - observable
      - id
    tags: malware
```
